### ISSUE TITLE
Allow build commands in package config

### ISSUE THREAD

**Issue by bahmutov** [kensho/multi-cypress#5]
Add ability to define custom build job commands, currently should use default
```
build-specs:
  stage: build
  script:
    - npm install
    - npm test
    - npm run build
```
